# --- 路径设置 ---
POSTERIOR_LIST="file_list.txt"  # 存储 posterior 文件路径的文件
CHROM_FILE="chrom.txt"
SCRIPT_DIR="./scripts"

# --- 任务参数 ---
THRESHOLD_P1=0.9
ITERATIONS=100
THREADS=8
POSTERIOR_MODE="auto"
TOP_ANCESTRIES=2
IGNORE_MINOR_ANCESTRY=true
PREPARED_POSTERIOR_DIR="prepared_posterior"
# --- 资源配置 (Slurm) ---
PARTITION="long"
CPUS=8
MEM="40G"

# --- 输出文件名 ---
FINAL_PROB_BED="all_chromosomes_final_prob.bed"
THRESHOLD_RESULT="global_threshold_97.5.txt"
PLOT_PREFIX="Manhattan_Cumulative_Prob"
